### PR TITLE
feat: add all domain management tools for SolanaAgentKit

### PR DESCRIPTION
**Pull request by ancienthumans**
Added AllDomains Features to Agent API:

Domain Resolution
Added agent.resolveAllDomains(domain) to resolve a domain's public key.

Lookup Owner
Added agent.getOwnedAllDomains(owner) to retrieve all domains owned by a specific owner.

Get Domains on TLD
Added agent.getOwnedDomainsForTLD(owner, tld) to fetch all domains owned under a specific TLD.

Get All Active TLDs
Added agent.getAllDomainsTLDs() to list all currently active TLDs.

Get All Registered Domains
Added agent.getAllRegisteredAllDomains() to fetch all registered domains across all TLDs.

Get User Main Domain
Added agent.getMainAllDomainsDomain(owner) to retrieve a user's favorite or main domain.. 
 This pull request was created for https://app.gib.work/bounties/57ed99db-7c9b-4239-ab05-5be02971f586 in an attempt to solve a bounty #15 . Payment for the bounty is immediately sent to the contributor after merge.

### CODE REVIEW

**Comment by thearyanag** [comment]
hey - can you pls follow this guide to also include the langchain tool class

https://docs.solanaagentkit.xyz/v0/guides/add_your_own_tool#2-implement-the-tool-class

**Comment by ancienthumans** [comment]
Added new tools to langchain tool class

**Comment by ancienthumans** [comment]
hey @thearyanag just want to check if everything's good!

**Comment by ancienthumans** [comment]
Maybe @arihantbansal could help out?

**Pull request closed without merging**
