### PR TITLE
updated the langchain tools

### PR DESCRIPTION
**Pull request by shubhiscoding**
Updated every class under langchain to implement Action interface without changing it's functionalities. 
 This pull request was created for https://app.gib.work/bounties/1a071256-33aa-4369-8d24-21839bcd4192 in an attempt to solve a bounty #53 . Payment for the bounty is immediately sent to the contributor after merge.

### CODE REVIEW

**Comment by thearyanag** [comment]
hey @shubhiscoding - awesome work just 1 thing will need to change 

the action for each tool needs to be independent, so can be in a file under src/action/index.ts

and then import those action in src/langchain/index.ts and use them there, as per the orignal tool without extending it to Action interface

**Comment by thearyanag** [comment]
for validator, you'll need to use zod

**Comment by shubhiscoding** [comment]
> hey @shubhiscoding - awesome work just 1 thing will need to change
> 
> the action for each tool needs to be independent, so can be in a file under src/action/index.ts
> 
> and then import those action in src/langchain/index.ts and use them there, as per the orignal tool without extending it to Action interface

So you what I'm thinking is to move all of class implementations that implement Action to src/action/index.ts and then all the classes in src/langchain/index.ts will have a private action object created for each tool and use that action object.
for example:
src/langchain/index.ts
```
export class SolanaBalanceTool extends Tool {
  private action: SolanaBalanceAction;
  name: string;
  description: string;

  constructor(solanaKit: SolanaAgentKit) {
    super();
    this.action = new SolanaBalanceAction(solanaKit);
    this.name = this.action.name;
    this.description = this.action.description;
  }

  async _call(input: string): Promise<string> {
    return this.action._call(input);
  }

  async handler(context: any, ...args: any[]): Promise<ActionResult> {
    return this.action.handler(context, ...args);
  }

  async validate(context: any, ...args: any[]): Promise<boolean> {
    return this.action.validate(context, ...args);
  }
}
```
src/actions/index.ts
```
export class SolanaBalanceAction extends Tool implements Action {
  name = "solana_balance";
  similes = ["check_balance", "get_wallet_balance"];
  description = `Get the balance of a Solana wallet or token account.

  If you want to get the balance of your wallet, you don't need to provide the tokenAddress.
  If no tokenAddress is provided, the balance will be in SOL.

  Inputs:
  tokenAddress: string, eg "So11111111111111111111111111111111111111112" (optional)`;
  examples: ActionExample[][] = [
    [
      {
        input: {
          message: {
            id: "1",
            content: { text: "Get my balance" },
            userId: "user1",
            timestamp: Date.now(),
          },
        },
        output: { success: true, data: { balance: "100 SOL" } },
      },
    ],
  ];

  constructor(private solanaKit: SolanaAgentKit) {
    super();
  }

   async _call(input: string): Promise<string> {
    try {
      const tokenAddress = input ? new PublicKey(input) : undefined;
      const balance = await this.solanaKit.getBalance(tokenAddress);

      return JSON.stringify({
        status: "success",
        balance: balance,
        token: input || "SOL",
      });
    } catch (error: any) {
      return JSON.stringify({
        status: "error",
        message: error.message,
        code: error.code || "UNKNOWN_ERROR",
      });
    }
  }

  handler: Handler = async (context, ...args) => {
    const input = args[0];
    const convert = async (): Promise<ActionResult> => {
      const promise_string = await this._call(input);
      return JSON.parse(promise_string);
    };
    return convert();
  };

  validate: Validator = async (context, ...args) => {
    const input = args[0];
    return typeof input === "string";
  };
}
```

Is that what you want?

**Comment by shubhiscoding** [comment]
Hey @thearyanag I have pushed changes, If I misunderstood the assignment do tell, I'll make the necessary changes

**Comment by shubhiscoding** [comment]
Hii @thearyanag I have made the changes you asked for and tested  it too, Please review it once!
Screenshot from 2024-12-28 17-12-45

**Comment by shubhiscoding** [comment]
@thearyanag are there any changes to be made?

**Comment by PurpleSquirrelMedia** [comment]
I reviewed your test, I think this can be submitted for a PR.

**Comment by shubhiscoding** [comment]
> I reviewed your test, I think this can be submitted for a PR.

Can it be merged then? @thearyanag?

**Comment by thearyanag** [comment]
hey @shubhiscoding - this looks good

- it's not working for single input functions
- what's the use of validator if you are not using it anywhere? 
- you have defined types from Eliza repo, but those are not used anywhere in the kit

**Comment by thearyanag** [comment]
closing this in favour of #72

**Comment by shubhiscoding** [comment]
Hii @thearyanag  I have fixed the single input function issue, also removed all  the unsed types and have added input vallidation in the lastest commit I just pushed, can you please reopen this?
Screenshot from 2024-12-30 08-14-08

**Comment by shubhiscoding** [comment]
I'm raising another PR #101 just review it once, If it doesn't fixes the issue close it and I won't raise a PR again for this issue.

**Pull request closed without merging**
