### PR TITLE
Feat: add langchain nextjs template

### LINKED ISSUE #58: NextJS Starter Repo
**Is your feature request related to a problem? Please describe.** Feature 
No example repo currently to show how to use in frontend applications 

**Describe the solution you'd like**
Make a repo similar to https://github.com/langchain-ai/langchain-nextjs-template/ which integrates the solana agent kit and people are able to interact directly on a UI

This should go under examples/nextjs-starter-repo

### PR DESCRIPTION
**Pull request by michaelessiet**
## Related Issue
Fixes #58 

## Changes Made
This PR adds the following changes:

- I added an examples directory with a README file which can be used to list templates, projects and examples built by the team and community
  
## Implementation Details

-  The template link contained in the README is a template I created using the Nextjs and Langchain template.
-  The template includes a proper implementation of the Solana Agent Kit and Langchain response streaming.

## Additional Notes

I believe that examples should be left out of library repos, not just because of bundle size but because the repo itself can get quite big and maintaining a monorepo never scales well.

## Checklist
- [x] I have tested these changes locally
- [x] I have updated the documentation

### CODE REVIEW

**Comment by thearyanag** [comment]
hey @michaelessiet - can you share a deployed link for it? 

+ we want it to be under `examples/nextjs-starter-repo` as originally mentioned, as we were restricting the repo a bit, so it won't face any issue

**Comment by michaelessiet** [comment]
I noticed your comment on #69 . How do you recommend we integrate tx signing using Privy? My example has the agent live on the server as if it were on the client the OpenAI API key would be exposed in the client bundle. Is a Privy server wallet adapter/integration being built for these cases?

**Comment by michaelessiet** [comment]
So I had the idea of creating my own embedded wallet implementation where a user connects their wallet extension (Phantom, Backpack), requests an auth challenge from the server, signs it, sends it back, it then gets verified on the server that the message sent has been properly signed. After that the challenge is deleted from the store/db, a jwt is created, then some kind of child wallet is created on the server and the secret key for that is stored on a Redis store. However, 2 issues
1. I don't think solana has a way to delegate spending of funds to another address/wallet or some kind of child wallet system.
2. The Nextjs API server route is stateless so the the Redis in-memory store won't work.

I checked out passkey but they're currently on waitlist and Privy doesn't give access to the server wallet's private key. At the moment I don't think there's a way to do this without potentially compromising the applications OpenAI API key or the user's private key. Your thoughts would be much welcome on this

**Comment by metasal1** [comment]
Hi Michael 

You can use Passkeys now - just generate a random UUID

**Comment by michaelessiet** [comment]
A random UUID works as the appId?

**Comment by metasal1** [comment]
For testing purposes yes.

**Comment by michaelessiet** [comment]
Ok, I'll give it a try. BTW those repos seem to be private

**Comment by michaelessiet** [comment]
Screenshot 2024-12-29 at 11 38 28

I seem to be getting this error

**Comment by michaelessiet** [comment]
@thearyanag this is the live link https://solana-agent-nextjs-starter-langchain.vercel.app/. I noticed that a PR has already been merged for this, however, I'm open to continue brainstorming the above discussion

**Comment by thearyanag** [comment]
image
hey @michaelessiet can you fix formatting issue here, will keep this repo as well

**Comment by michaelessiet** [comment]
@thearyanag fixed

**Comment by thearyanag** [comment]
hey @michaelessiet looks good 

just letting you know, as we have already merged 1 existing PR, we wont' be able to award for this - if that's fine - I can go ahead and merge this. 

We'll give proper attribution

**Comment by michaelessiet** [comment]
Sure no worries. However, once I've updated my vercel-ai-sdk PR with the actions framework that is yet to be merged I'm thinking of adding an example for Expo (React Native) apps. Would that qualify for the bring your own idea bounty?

**Comment by thearyanag** [comment]
hey @michaelessiet , the expo app would be really awesome - we would def reward that

**Pull request merged**
