### PR TITLE
feat: Implement framework-independent Action interface

### PR DESCRIPTION
**Pull request by FahriBilici**
This PR implements a framework-independent Action interface inspired by Eliza, making the tools more flexible and reusable across different frameworks.

Changes:
- Created independent actions under `src/actions/`
- Implemented Zod validation for type safety
- Converted all LangChain tools to use actions
- Added natural language matching with similes
- Improved error handling and response formats

### CODE REVIEW

**Comment by arihantbansal** [comment]
Looks great! Have you tested this out locally? If so, could you please attach screenshots for it

**Comment by FahriBilici** [comment]
is this okay?

screenshot

**Comment by thearyanag** [comment]
@FahriBilici this is awesome 

as i can see, not all tools are converted to actions, is it something WIP

**Comment by arihantbansal** [comment]
@FahriBilici Why is that in some action files you are using the `agent.action` format to resolve, whereas in some of the action tools you are copying from the tool file itself? Please maintain uniformity. Better to separate tools and actions imo, wdyt @thearyanag?

**Comment by FahriBilici** [comment]
> @FahriBilici Why is that in some action files you are using the `agent.action` format to resolve, whereas in some of the action tools you are copying from the tool file itself? Please maintain uniformity. Better to separate tools and actions imo, wdyt @thearyanag?

I tried to make all of them using tools. Let me know your thoughts

**Comment by arihantbansal** [comment]
> > @FahriBilici Why is that in some action files you are using the `agent.action` format to resolve, whereas in some of the action tools you are copying from the tool file itself? Please maintain uniformity. Better to separate tools and actions imo, wdyt @thearyanag?
> 
> I tried to make all of them using tools. Let me know your thoughts

Looks great. Only one question, do you think it's better to `transfer(agent, xyz)` or `agent.transfer(xyz)` @thearyanag ?

I'm still undecided, but I think `agent.transfer` makes more sense in this context. As each action defines what the agent can do.

**Comment by FahriBilici** [comment]
@thearyanag any comment?

**Comment by thearyanag** [comment]
hey @FahriBilici - I was trying to test it out, but was facing many bugs

can you just share a working video for it

**Comment by FahriBilici** [comment]
> hey @FahriBilici - I was trying to test it out, but was facing many bugs
> 
> can you just share a working video for it

How are you testing it? I run tests in auto mode.

**Comment by thearyanag** [comment]
I tested the pyth price feed, the prompt I used was

price of 49f6b65cb1de6b10eaf75e7c03ca029c306d0357e91b5311b175084a5ad55688 feed

**Comment by FahriBilici** [comment]
@thearyanag I fixed the bug and here is the video 

https://github.com/user-attachments/assets/354bed40-7555-40d0-a2bf-336de26f04a9

**Comment by FahriBilici** [comment]
@thearyanag done

**Comment by thearyanag** [comment]
hey @FahriBilici - just checked, not every tool under LangChain is using the action, any specific reason?

**Comment by FahriBilici** [comment]
@thearyanag I have made some changes, but I noticed a few tools are missing as actions. I will add them soon. Do you have any other feedback in the meantime?

**Comment by thearyanag** [comment]
heyo @FahriBilici - can you dm me on twitter?

**Comment by FahriBilici** [comment]
> heyo @FahriBilici - can you dm me on twitter?

I sent

**Pull request merged**
