### PR TITLE
Add Nextjs example

### LINKED ISSUE #58: NextJS Starter Repo
**Is your feature request related to a problem? Please describe.** Feature 
No example repo currently to show how to use in frontend applications 

**Describe the solution you'd like**
Make a repo similar to https://github.com/langchain-ai/langchain-nextjs-template/ which integrates the solana agent kit and people are able to interact directly on a UI

This should go under examples/nextjs-starter-repo

### PR DESCRIPTION
**Pull request by DogukanGun**
# Pull Request Description

## Related Issue
Fixes #58

## Changes Made
This PR adds the following changes:

- Adding nextjs example
- Creating agent by user private key and OpenAI Key
- Integrates langchain and uses OpenAI
- ChatGPT base UI
  
## Implementation Details

- NextJS is used.
- Langchain is used.

## Transaction executed by agent 

Example transaction: 

## Prompt Used

```
npm run dev
```

## Additional Notes

The tweet about the pr is [here](https://x.com/Dogukan_Gndgn/status/1872355363942723909)

## Checklist
- [x] I have tested these changes locally
- [x] I have updated the documentation
- [x] I have added a transaction link
- [x] I have added the prompt used to test it

### CODE REVIEW

**Comment by thearyanag** [comment]
can you share a deployed link?

**Comment by DogukanGun** [comment]
> can you share a deployed link?

Here is the [web page](https://solana-agent-kit.vercel.app/) . Please consider that the app contains OpenAI key which has 10$ credits, the wallet has not funding and the cluster is mainnet.

**Comment by thearyanag** [comment]
great work @DogukanGun 

image

the chat history on left side is not showing currently, can you pls fix it

for the wallet, can you use something like privy to create embedded wallet on your frontend and auto-approve each transaction?

**Comment by thearyanag** [comment]
closed in favour of #75

**Pull request closed without merging**
