### PR TITLE
Support Resolving AD Domains

### PR DESCRIPTION
**Pull request by adpthegreat**
This PR contains methods as that implement the following logic 

Agent can resolve domains public key

i.e. agent.resolveAllDomains(domain)

### Lookup Owner

Agent can get all domains owned

i.e. agent.getOwnedAllDomains(owner)

### Get Domains on TLD

Agent can get all domains for a specific TLD

i.e. agent.getOwnedDomainsForTLD(owner, tld)

### Get All Active TLDs

Agent can fetch all the current active TLDs

i.e. agent.getAllDomainsTLDs()

### Get All Registered All Domains

Return all the domains for all the TLDs

i.e. agent.getAllRegisteredAllDomans()

### Get User Main Domain

Get the user’s favourite / main domain i.e. agent.getMainAllDomainsDomain(owner). 
 This pull request was created for https://app.gib.work/bounties/57ed99db-7c9b-4239-ab05-5be02971f586 in an attempt to solve a bounty #15 . Payment for the bounty is immediately sent to the contributor after merge.

### CODE REVIEW

**Comment by thearyanag** [comment]
hey - can you pls follow this guide to also include the langchain tool class

https://docs.solanaagentkit.xyz/v0/guides/add_your_own_tool#2-implement-the-tool-class

**Comment by adpthegreat** [comment]
Alright, on it right now

**Comment by adpthegreat** [comment]
Screenshot 2024-12-21 at 20 53 25
Screenshot 2024-12-21 at 20 53 43
@thearyanag I've written the langchain tool class and implemented the methods in the bounty, also wrote tests to show that they work as intended , please can you review this, thank you

**Comment by adpthegreat** [comment]
@metasal1 please review my bounty submission , thank you !

**Comment by adpthegreat** [comment]
Hi @thearyanag @metasal1 still waiting for your review/feedback thank you, just rebased now so my code is up to date

**Comment by thearyanag** [comment]
hey @adpthegreat - thanks was just going over your PR

**Comment by adpthegreat** [comment]
Alright I'm active currently to make any changes you request, thanks

**Pull request merged**
